language: R
sudo: false
cache: packages

warnings_are_errors: true

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'install.packages("rPython")'
  - Rscript -e 'covr::coveralls()'
