language: R
sudo: required
cache: packages

before_install:
  - sudo apt-get install python2.7

warnings_are_errors: true

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'install.packages("rPython")'
  - Rscript -e 'covr::coveralls()'
